---
# tasks file for docker
- apt_key:
    url: "https://apt.dockerproject.org/gpg"
    state: present

- apt_repository:
      repo: deb http://apt.dockerproject.org/repo {{ ansible_distribution }}-{{ ansible_distribution_release }} main
      state: present
      filename: docker
      update_cache: yes

# {{ ansible_distribution_release }}
