---
# tasks file for docker
- name: install required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: remove old and distro own docker
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  when: (ansible_distribution == 'Debian')

- apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  when: (ansible_distribution == 'Ubuntu')

- apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
  when: (ansible_distribution == 'Debian') or
        (ansible_distribution == 'Ubuntu')

- copy:
    content: |
            Package: docker-engine
            Pin: version {{ docker_version }}-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
            Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/pin-docker"
    mode: 0440
    owner: root
    group: root
  when: docker_version is defined and docker_version != ""

- name: install docker-engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: add {{ docker_user }} to docker group
  user:
    name: '{{ docker_user }}'
    groups: docker
    append: yes
  when: docker_user is defined and docker_user != ""
