---
# handlers file for docker
- apt_key:
    url: "https://apt.dockerproject.org/gpg"
    state: present

- name: test
  command: echo {{ ansible_distribution }}

- apt_repository:
    repo: deb http://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main
    state: present
    filename: docker
    update_cache: yes
  when: (ansible_distribution == 'Debian') or
        (ansible_distribution == 'Ubuntu')

- copy:
    content: |
            Package: docker-engine
            Pin: version {{ docker_version }}-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
            Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/pin-docker"
    mode: 0440
    owner: root
    group: root
  when: docker_version is defined and docker_version != ""

- name: install docker-engine
  apt:
    name: docker-engine
    state: present
    update_cache: yes
